spring:
  application:
    name: order

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?useSSL=false&amp&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    redis:
      host: 192.168.43.107
      password: 123456

  rabbitmq:
    addresses: 192.168.43.107
    password: admin
    username:admin
    port: 5672
pq: 12

server:
  port: 8081
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: order.common.entity
