version: '3'

services:
  koel:
    image: phanan/koel
    container_name: koel
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_USERNAME=koel
      - DB_PASSWORD=koel
      - DB_DATABASE=koel
      - LASTFM_API_KEY=6bb5a01cd16ef392adb81a8e338b88ad
      - LASTFM_API_SECRET=a63dd9a24807f288f960d7eb3cdf412e
      - SPOTIFY_CLIENT_ID=c3d88d3a15e54efbbf85b20c8386eeb0
      - SPOTIFY_CLIENT_SECRET=e7ea978b079c4153b8c115247e16b480
      - TRANSCODE_FLAC=false
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes

  database:
    image: mysql/mysql-server:5.7
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=koel

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local
  search_index:
    driver: local
