version: '3'

services:
  koel:
    image: phanan/koel
    container_name: koel
    ports:
      - 81:80
    environment:
      - TZ=Asia/Shanghai
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=0820nCf9270
      - DB_DATABASE=koel
      - STREAMING_METHOD=x-sendfile
      - TRANSCODE_FLAC=false
      - OUTPUT_BIT_RATE=320
    volumes:
      - /root/koel/music:/music
      - /root/assets/img/covers:/var/www/html/public/img/covers
      - /root/assets/img/artists:/var/www/html/public/img/artists
      - /root/koel/index:/var/www/html/storage/search-indexes
    restart: always
    networks:
      - mynet
networks:
  mynet:
    external: true
