name: 初始化私服

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Init Trigger'
        required: false
        default: 'warning'
      tags:
        description: '初始化私服'

jobs:
  job1:
    name: Init Self-Hosted Server
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2

      - name: 初始化服务器-重启前
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          HOST: ${{ secrets.HOST }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          PORT: ${{ secrets.PORT }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: 22
          connect_timeout: 10s
          first_ssh: |
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step1/sync_time_zone.sh)
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step1/secure.sh) $PORT
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step1/config_network.sh) $HOST_NAME $HOST
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step1/config_env.sh) $GH_TOKEN
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step1/config_ufw.sh) $PORT
      # last_ssh: |
      #   reboot

      - name: 重启服务器
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        continue-on-error: true
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: 22
          connect_timeout: 10s
          first_ssh: |
            reboot

      - name: 等待服务器重启完成...
        run: |
          sleep 15s

      - name: 初始化服务器-重启后
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          PORT: ${{ secrets.PORT }}
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          first_ssh: |
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step2/config_node.sh)
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step2/config_docker.sh)
            /bin/bash <(curl -L https://raw.githubusercontent.com/nichuanfang/config-server/master/linux/bash/step2/config_python.sh)
          # last_ssh: |
          #   reboot

      # # 更新端口 替换默认的22端口
      # - name: 更新端口
      #   uses: jon-grey/github-actions-secrets-creator@v1
      #   with:
      #     name: PORT
      #     value: ${{ secrets.PORT }}
      #     pa_token: ${{ secrets.GH_TOKEN }}
