name: 初始化私服

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Init Trigger'
        required: false
        default: 'warning'
      tags:
        description: '初始化私服'

jobs:
  job1:
    name: Init Self-Hosted Server
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.2

      - name: 初始化服务器-重启前
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        continue-on-error: false
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          PORT: ${{ secrets.PORT }}
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          first_ssh: |

          # scp: |
          #   './test/*' => /home/github/test/
          #   ./test/test1* => /home/github/test/test1/
          #   ./test/test*.csv => "/home/github/test/test2/"
          # last_ssh: |
          # curl -L https://api.day.app/${{ secrets.BARK_TOKEN }}/crawler镜像已更新

      - name: 同步时区
        run: |
          ./linux/bash/step1/sync_time_zone.sh

      # 重启服务器

      # - name: 等待服务器重启完成...
      #   run: |
      #     sleep 10s

      # # 更新端口 替换默认的22端口
      # - name: 更新端口
      #   uses: jon-grey/github-actions-secrets-creator@v1
      #   with:
      #     name: PORT
      #     value: ${{ secrets.PORT }}
      #     pa_token: ${{ secrets.GH_TOKEN }}
