version: 7
profiles:
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 149.104.22.251
      port: 60456
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      forwardedPorts: []
      scripts: []
      privateKeys: []
    weight: -1
    name: 科学上网
    id: ssh:custom::ab6fdf41-9d0e-4a1f-9e21-13e9fda1b8ae
groups: []
configSync:
  parts: {}
  host: ''
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  love-shell: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Earthsong
    foreground: '#e5c7a9'
    background: '#292520'
    cursor: '#f6f7ec'
    colors:
      - '#121418'
      - '#c94234'
      - '#85c54c'
      - '#f5ae2e'
      - '#1398b9'
      - '#d0633d'
      - '#509552'
      - '#e5c6aa'
      - '#675f54'
      - '#ff645a'
      - '#98e036'
      - '#e0d561'
      - '#5fdaff'
      - '#ff9269'
      - '#84f088'
      - '#f6f7ec'
  bell: visual
  customColorSchemes:
    - name: base2tone-heath-light
      foreground: '#575158'
      background: '#fbfaf9'
      cursor: '#eaa8f0'
      colors:
        - '#222022'
        - '#8f6c93'
        - '#cc8c33'
        - '#ffd599'
        - '#9a819c'
        - '#b87414'
        - '#cb79d2'
        - '#9e999f'
        - '#635f63'
        - '#d9b98c'
        - '#2f2d2f'
        - '#575158'
        - '#6f6b70'
        - '#eaa8f0'
        - '#c38022'
        - '#fbfaf9'
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  cursor: underline
  fontSize: 15
  linePadding: 2
  font: Cascadia Code SemiBold
  autoOpen: false
ssh:
  knownHosts:
    - host: 149.104.22.251
      port: 60456
      type: ecdsa-sha2-nistp256
      digest: /+HiGaoCT+g47mzS8qYMbhb0TW8xZnBS/ALfevc3KTs=
clickableLinks: {}
accessibility: {}
appearance:
  vibrancyType: fluent
  frame: native
  vibrancy: true
hacks:
  disableGPU: true
providerBlacklist: []
commandBlacklist: []
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
language: zh-CN
profileBlacklist: []
loveShell:
  apiKey: 0820nCf9270
  model: tabby
highlightPlugin:
  highlightKeywords:
    - text: ERROR
      enabled: true
      isRegExp: false
      foreground: true
      foregroundColor: 0
      background: true
      backgroundColor: 1
      bold: false
    - text: WARN
      enabled: true
      isRegExp: false
      foreground: true
      foregroundColor: 0
      background: true
      backgroundColor: 3
      bold: false
    - text: INFO
      enabled: true
      isRegExp: false
      foreground: true
      foregroundColor: 0
      background: true
      backgroundColor: 6
      bold: false
    - text: 错误
      enabled: true
      isRegExp: false
      foreground: true
      foregroundColor: 0
      background: true
      backgroundColor: 1
      bold: false
    - text: 警告
      enabled: true
      isRegExp: false
      foreground: true
      foregroundColor: 0
      background: true
      backgroundColor: 3
      bold: false
    - text: 信息
      enabled: true
      isRegExp: false
      foreground: true
      foregroundColor: 0
      background: true
      backgroundColor: 6
      bold: false
  highlightEnabled: true
